module.exports = {sendTranslations: [
        "send", 
        "envoyer", 
        "enviar", 
        "send me", 
        "senden", 
        "oka maru", 
        "mata dapan", 
        "maru", 
        "diyanko", 
        "oneee", 
        "wysłać", 
        "Sent", 
        "one", 
        "danna", 
        "ewnna", 
        "ewpm", 
        "sent", 
        "ewn", 
        "එවන්න", 
        "ඔනෙ", 
        "ඔන", 
        "දාන්න", 
        "දම්", 
        "එවපං", 
        "දහම්", 
        "එවපන්", 
        "දපන්", 
        "දාපන්", 
        "දාපම්", 
        "ඔනා", 
        "ඔනේ", 
        "එවහන්", 
        "One", 
        "දෙන්නකො", 
        "SEND"
    ]
};
